### ISSUE TITLE
Problem: Not following a formal specification leads to trouble when upgrading cardano-sl

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/cardano-wallet#14]
Solution: follow the [Cardano Wallet Specification](https://cardanodocs.com/technical/formal-specification-for-a-cardano-wallet/)

**Comment by clacke** [comment]
Will be printing out a booklet for bed-time reading.

**Comment by sjmackenzie** [comment]
Using https://github.com/input-output-hk/cardano-sl/tree/develop/wallet-new as our wallet backend which implements the Cardano Wallet Specification means we automatically follow the specification. It'll probably be done by July 2018.
