### ISSUE TITLE
Update Cardano wallet page layout

### ISSUE THREAD

**Issue by dapyh17d4** [fractalide/cardano-wallet#30]
Please update the page (https://fractalide.com/cardano-wallet/) according to the designs below.

New icons are in this assets folder
https://drive.google.com/open?id=1UpnJCA0GZNy1vwrwgDqWvdLefNrzFD2Q

Desktop
![wallet-02](https://user-images.githubusercontent.com/39090829/41494913-61dcf11c-714e-11e8-8397-34558fc05c57.png)

Tablet
![wallet-tab-02](https://user-images.githubusercontent.com/39090829/41494915-6be23a6e-714e-11e8-90a8-b0293b4b6aae.png)

Phone
![wallet-phone-02](https://user-images.githubusercontent.com/39090829/41494917-6f603b96-714e-11e8-8608-c31265532444.png)

cc @sjmackenzie

**Comment by miguelsimoni** [comment]
This issue belongs to another project...

https://github.com/fractalide/fractalide-website-styx

Closed with: https://github.com/fractalide/fractalide-website-styx/pull/180
